---
abstract: 'Release tests for source encoding'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MojibakeTests
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0
  Test::Mojibake: 0
  Unicode::CheckUTF8: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/creaktive/Dist-Zilla-Plugin-MojibakeTests/issues
  homepage: https://github.com/creaktive/Dist-Zilla-Plugin-MojibakeTests
  repository: git://github.com/creaktive/Dist-Zilla-Plugin-MojibakeTests.git
version: 0.5
