---
abstract: 'Release tests for source encoding'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-MojibakeTests
requires:
  Dist::Zilla: 0
  Test::Mojibake: 0
resources:
  bugtracker: http://github.com/creaktive/Dist-Zilla-Plugin-MojibakeTests/issues
  repository: git://github.com/creaktive/Dist-Zilla-Plugin-MojibakeTests.git
version: 0.3
